<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find swerve_drive_robot_description)/urdf/common.xacro"/>
	<xacro:include filename="$(find swerve_drive_robot_description)/urdf/base/base.gazebo.xacro"/>

	<xacro:property name="base_height" value="0.15"/>
    <xacro:property name="base_width" value="0.09"/>
    <xacro:property name="base_depth" value="0.015"/>
    <xacro:property name="base_mass" value="0.5"/>

	
	<xacro:macro name="base_v0" params="link_name parent *joint_origin">
		<joint name="${link_name}_joint" type="fixed">
			<xacro:insert_block name="joint_origin"/>
			<parent link="${parent}"/>
			<child link="${link_name}"/>
		</joint>

		<link name="${link_name}">
			<visual>
				<geometry>
					<mesh filename="package://swerve_drive_robot_description/meshes/stl/base.STL"/>
				</geometry>
				<origin xyz="0 0 0" />
				<material name="gray"/>
			</visual>
			<collision>
				<geometry>
					<box size="${base_height} ${base_width} ${base_depth}"/>
				</geometry>
				<origin xyz="0 0 ${base_depth/2}" />
			</collision>
			<inertial>
				<origin xyz="0 0 ${base_depth/2}"/>
				<xacro:box_inertial mass="${base_mass}" height="${base_height}" width="${base_width}" depth="${base_depth}"/>
			</inertial>
		</link>
	</xacro:macro>

</robot>